### ISSUE TITLE
【验证】请激活一下，非常感谢

### ISSUE THREAD

**Issue by stlion** [Errerer/DalamudPlugins#13]
其实之前（https://github.com/Errerer/DalamudPlugins/issues/11#issue-2310394082）
已申请Auto的激活，不过不知道是不是因为helper和auto是分开的，而当时没有说明，所以大佬E说OK了之后，auto还是没有验证激活。
![屏幕截图 2024-05-26 122718](https://github.com/Errerer/DalamudPlugins/assets/9400418/0f93776f-eb8b-4dbc-ba13-11b1d16b090a)

所以重新贴一次，申请两个激活：
【auto】S8AC3EB6556B18EB545D096F02B0545CD
【helper】S047AF9933EF50CABB28B10A52490E6D7

麻烦大佬E了，感谢~

**Comment by Errerer** [comment]
active again

**Comment by stlion** [comment]
收到。再次感谢大佬E！
