### ISSUE TITLE
【验证】请激活一下，感谢

### ISSUE THREAD

**Issue by stlion** [Errerer/DalamudPlugins#18]
之前auto用5003版本已激活过（https://github.com/Errerer/DalamudPlugins/issues/13 ），后来更新国服658后加载错误，今天更新auto到5004版本后能加载，但无激活，所以来请大佬E激活：S047AF9933EF50CABB28B10A52490E6D7（auto的账号凭证），谢谢先。

**Comment by Errerer** [comment]
ok

**Comment by stlion** [comment]
感谢~~
