### ISSUE TITLE
【验证】麻烦E佬验证一下！

### ISSUE THREAD

**Issue by Kooord** [Errerer/DalamudPlugins#7]
S766F61922DA9D90542AED5256E361866

**Comment by Kooord** [comment]
非常感谢！

**Comment by Errerer** [comment]
1

**Comment by Kooord** [comment]
谢谢E佬！

**Comment by Kooord** [comment]
> 1

E佬qwq！更新后过期了！！！
S99DD403AD7B5B7D567332BB516040866
CCBD64C5E3BB2DA4EC117E2403E93254B
